# Generated by Django 3.2.4 on 2021-06-25 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rekrutmen', '0002_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='member_id',
        ),
        migrations.AddField(
            model_name='job',
            name='hdc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
