# Generated by Django 3.2.4 on 2021-06-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutmen', '0008_auto_20210627_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
