# Generated by Django 3.2.4 on 2021-06-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutmen', '0009_alter_test_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='tests',
        ),
        migrations.AddField(
            model_name='job',
            name='tests',
            field=models.ManyToManyField(null=True, to='rekrutmen.Test'),
        ),
    ]
