# Generated by Django 3.2.4 on 2021-06-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutmen', '0010_auto_20210627_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='tests',
            field=models.ManyToManyField(to='rekrutmen.Test'),
        ),
    ]
