# Generated by Django 3.2.4 on 2021-07-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutmen', '0011_alter_job_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tests',
            field=models.ManyToManyField(to='rekrutmen.Test'),
        ),
    ]
