# Generated by Django 3.2.4 on 2021-07-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutmen', '0012_member_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblist',
            name='tests',
            field=models.ManyToManyField(to='rekrutmen.Test'),
        ),
    ]
